# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OrtografieQuiz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OrtografieQuiz
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  target 'OrtografieQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
